# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6aa4e290597188238a71a5758c216f8f53ae0e175f9b8df95d2a6c42ba676736704c8ba136754d52a1ef7d6675aa3726e5db83a765592470ccf236e3c7429ceb

test:
  secret_key_base: 91fe26747488316065b81fa353753acc31d2119035e0add70f1574590eeb15ce7cad950360d9a37ecbb5ac5fbc55c6172c392e1edcb4a412588ba5280c7320c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
